### ISSUE TITLE
Assets Added via Asset Fields with Dynamic Paths Not Being Saved

### ISSUE THREAD

**Issue by kerns** [verbb/vizy#27]
**Description**
I created a new asset field for use in a Vizy block, using the same dynamic path setup used by the existing asset field that was already implemented successfully on the main entry. My only change was to add an extra subfolder to the path, so that content built in Vizy is stored with the entry in a subfolder of it's own.

But assets I add and save through the Vizy, while they do appear in the Vizy editor, are stuck in my temporary folder. They don't create subfolders and their paths cannot be rendered in templates.

In testing, if I take the same newly created assets field I had designated for the Vizy block and move it to the entry itself, it works as expected. Subfolders are generated and assets are collected.

**Steps to reproduce**
1. Create a field with a dynamic path based on the entry id or slug
2. Incorporate it into a Vizy block
3. Attach assets, ...see if they land where they should

**Additional info**
This is a S3 volume. 👀

**Comment by engram-design** [comment]
This might be similar to https://github.com/verbb/vizy/issues/22 ?

I assume you might be using `{owner.slug}/some-folder` or similar?

**Comment by kerns** [comment]
Correct.
```
Automobiles/{postDate|date('Y')}/{{postDate|date('m')}}/{{model.one().slug}}-{{id}}/extra-media/
```

**Comment by engram-design** [comment]
So note the use of `owner` to get the owner element, just like you would with a Matrix field. Should be working as per the `dev-craft-3` branch.

**Comment by kerns** [comment]
Noted. :) Though I am uncertain about how to parent these correctly. Maybe...

`Automobiles/{postDate|date('Y')}/{{postDate|date('m')}}/{{owner.model.one().slug}}-{{owner.id}}/extra-media/`

**Comment by engram-design** [comment]
Whenever you're referring to something on the entry, use `owner`.

`Automobiles/{owner.postDate|date('Y')}/{{owner.postDate|date('m')}}/{{owner.model.one().slug}}-{{owner.id}}/extra-media/`

I'm not sure what `model` is here, but assuming its a custom field on the entry. If you wanted the slug for the entry, use `owner.slug`. Otherwise, you're using the year, month of the entry post date, and the entry id.

**Comment by kerns** [comment]
Yes this was the first thing I tried – I parented everything w/ `owner` but when it didn't work I thought maybe to remove it from the post date.

I did `composer update` w/ `dev-craft-3 as 1.0.1` but I still have the same issue with assets. Maybe it is the complexity of this `model` field that is itself a dynamic construct. 😬It is a custom related entry field on the entry, as you guessed...

<img width="277" alt="Screen Shot 2021-05-23 at 16 22 37" src="https://user-images.githubusercontent.com/20254/119264458-9a8f8780-bbe3-11eb-8899-2d7241794a58.png">

But the entries are themselves dynamic... so...this is maybe too edge-casey, perhaps outside the scope of what is possible for you to figure out from there.

<img width="921" alt="Screen Shot 2021-05-23 at 16 25 23" src="https://user-images.githubusercontent.com/20254/119264881-18a05e00-bbe5-11eb-80b8-df1400808e12.png">

<img width="541" alt="Screen Shot 2021-05-23 at 16 22 59" src="https://user-images.githubusercontent.com/20254/119264878-176f3100-bbe5-11eb-93e4-950c1a84a9d4.png">

**Comment by adrienpicard** [comment]
I'm having similar issues with a simpler setup. When saving the entry, there is no`owner.slug` folder created. Files uploaded in the block stay in the tmp folder.

<img src="https://user-images.githubusercontent.com/1401142/119318880-b5a8d880-bc71-11eb-8f4c-4ee36ebdd29c.png" width="400">

**Comment by engram-design** [comment]
Good catch. Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/vizy/releases/tag/1.0.3)
